const students = [
  { email: "ahmedezzatomar6@gmail.com", code: "bqCIfxHgHg" }, // 1
  { email: "", code: "" }, // 2
  { email: "", code: "" }, // 3
  { email: "", code: "" }, // 4
  { email: "", code: "" }, // 5
  { email: "", code: "" }, // 6
  { email: "", code: "" }, // 7
  { email: "", code: "" }, // 8
  { email: "", code: "" }, // 9
  { email: "", code: "" }, // 10
  { email: "", code: "" }, // 11
  { email: "", code: "" }, // 12
  { email: "", code: "" }, // 13
  { email: "", code: "" }, // 14
  { email: "", code: "" }, // 15
  { email: "", code: "" }, // 16
  { email: "", code: "" }, // 17
  { email: "", code: "" }, // 18
  { email: "", code: "" }, // 19
  { email: "", code: "" }, // 20
  { email: "", code: "" }, // 21
  { email: "", code: "" }, // 22
  { email: "", code: "" }, // 23
  { email: "", code: "" }, // 24
  { email: "", code: "" }, // 25
  { email: "", code: "" }, // 26
  { email: "", code: "" }, // 27
  { email: "", code: "" }, // 28
  { email: "", code: "" }, // 29
  { email: "", code: "" }, // 30
  { email: "", code: "" }, // 31
  { email: "", code: "" }, // 32
  { email: "", code: "" }, // 33
  { email: "", code: "" }, // 34
  { email: "", code: "" }, // 35
  { email: "", code: "" }, // 36
  { email: "", code: "" }, // 37
  { email: "", code: "" }, // 38
  { email: "", code: "" }, // 39
  { email: "", code: "" }, // 40
  { email: "", code: "" }, // 41
  { email: "", code: "" }, // 42
  { email: "", code: "" }, // 43
  { email: "", code: "" }, // 44
  { email: "", code: "" }, // 45
  { email: "", code: "" }, // 46
  { email: "", code: "" }, // 47
  { email: "", code: "" }, // 48
  { email: "", code: "" }, // 49
  { email: "", code: "" }, // 50
  { email: "", code: "" }, // 51
  { email: "", code: "" }, // 52
  { email: "", code: "" }, // 53
  { email: "", code: "" }, // 54
  { email: "", code: "" }, // 55
  { email: "", code: "" }, // 56
  { email: "", code: "" }, // 57
  { email: "", code: "" }, // 58
  { email: "", code: "" }, // 59
  { email: "", code: "" }, // 60
  { email: "", code: "" }, // 61
  { email: "", code: "" }, // 62
  { email: "", code: "" }, // 63
  { email: "", code: "" }, // 64
  { email: "", code: "" }, // 65
  { email: "", code: "" }, // 66
  { email: "", code: "" }, // 67
  { email: "", code: "" }, // 68
  { email: "", code: "" }, // 69
  { email: "", code: "" }, // 70
  { email: "", code: "" }, // 71
  { email: "", code: "" }, // 72
  { email: "", code: "" }, // 73
  { email: "", code: "" }, // 74
  { email: "", code: "" }, // 75
  { email: "", code: "" }, // 76
  { email: "", code: "" }, // 77
  { email: "", code: "" }, // 78
  { email: "", code: "" }, // 79
  { email: "", code: "" }, // 80
  { email: "", code: "" }, // 81
  { email: "", code: "" }, // 82
  { email: "", code: "" }, // 83
  { email: "", code: "" }, // 84
  { email: "", code: "" }, // 85
  { email: "", code: "" }, // 86
  { email: "", code: "" }, // 87
  { email: "", code: "" }, // 88
  { email: "", code: "" }, // 89
  { email: "", code: "" }, // 90
  { email: "", code: "" }, // 91
  { email: "", code: "" }, // 92
  { email: "", code: "" }, // 93
  { email: "", code: "" }, // 94
  { email: "", code: "" }, // 95
  { email: "", code: "" }, // 96
  { email: "", code: "" }, // 97
  { email: "", code: "" }, // 98
  { email: "", code: "" }, // 99
  { email: "", code: "" }, // 100
];

